server:
  host: localhost
  port: 8080
system:
  router-prefix: ""
mysql:
  port: 3306
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: test
  username: root
  password: root599926
  path: 127.0.0.1
jwt:
  signing-key: 6ae776bc-2fa2-4fb2-85f3-ba1594a10d02
  expires-time: 7d
  buffer-time: 1d
captcha:
  key-long: 6
  img-width: 240
  img-height: 80
aliyun-oss:
  endpoint:
  access-key-id:
  access-key-secret:
  bucket-name:
  bucket-url:
  base-path:
