definitions:
  response.CaptchaResponse:
    properties:
      captchaId:
        type: string
      captchaImg:
        type: string
    type: object
  response.LoginResponse:
    properties:
      token:
        type: string
      user:
        $ref: '#/definitions/response.UserResponse'
    type: object
  response.PageInfoResponse:
    properties:
      data: {}
      total:
        type: integer
    type: object
  response.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  response.UserResponse:
    properties:
      nickName:
        type: string
      userId:
        type: integer
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /base/captcha:
    get:
      description: 获取验证码
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.CaptchaResponse'
                msg:
                  type: string
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  type: object
                msg:
                  type: string
              type: object
      summary: 获取验证码
      tags:
      - Bases
  /base/login:
    post:
      description: 用户登录
      parameters:
      - description: 用户名
        in: body
        name: username
        required: true
        schema:
          type: string
      - description: 密码
        in: body
        name: password
        required: true
        schema:
          type: string
      - description: 验证码
        in: body
        name: captcha
        schema:
          type: string
      - description: 验证码ID
        in: body
        name: captchaId
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: 返回包括用户信息, token
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.LoginResponse'
                msg:
                  type: string
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  type: object
                msg:
                  type: string
              type: object
      summary: 登录
      tags:
      - Bases
  /base/register:
    post:
      description: 注册用户
      parameters:
      - description: 用户名
        in: body
        name: username
        required: true
        schema:
          type: string
      - description: 密码
        in: body
        name: password
        required: true
        schema:
          type: string
      - description: 昵称
        in: body
        name: nickName
        schema:
          type: string
      - description: 验证码
        in: body
        name: captcha
        schema:
          type: string
      - description: 验证码ID
        in: body
        name: captchaId
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: 返回包括用户信息
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.UserResponse'
                msg:
                  type: string
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  type: object
                msg:
                  type: string
              type: object
      summary: 注册
      tags:
      - Bases
  /deleteUserById/{userId}:
    delete:
      description: 用户删除
      parameters:
      - description: 用户ID
        in: path
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  type: object
                msg:
                  type: string
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  type: object
                msg:
                  type: string
              type: object
      summary: 根据ID删除用户
      tags:
      - Users
  /fileUploadAndDownload/upload:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: 上传文件示例
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: 上传文件示例,返回包括文件详情
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  type: object
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 上传文件示例
      tags:
      - ExaFileUploadAndDownload
  /user/changePassword:
    post:
      description: 修改密码
      parameters:
      - description: 原密码
        in: body
        name: password
        required: true
        schema:
          type: string
      - description: 新密码
        in: body
        name: newPassword
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  type: object
                msg:
                  type: string
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  type: object
                msg:
                  type: string
              type: object
      summary: 修改密码
      tags:
      - Users
  /user/getUsers:
    post:
      description: 获取用户列表
      parameters:
      - description: 页码
        in: body
        name: page
        required: true
        schema:
          type: integer
      - description: 条数
        in: body
        name: pageSize
        required: true
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.PageInfoResponse'
                msg:
                  type: string
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  type: object
                msg:
                  type: string
              type: object
      summary: 获取用户列表
      tags:
      - Users
swagger: "2.0"
